apiVersion: v1
kind: Service
metadata:
  name: statsd-http-prod
  namespace: prod
spec:
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 80
    name: graphite-www
  type: LoadBalancer  
  selector:
    app: graphite-prod