version: "3.3"
services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - graphite-prod
    restart: always
    environment:
      STATSD_HOST: graphite-prod
      STATSD_PORT: 8125
    volumes:
      - .:/usr/src/app

  graphite-prod:
    image: graphiteapp/graphite-statsd:1.1.10-5
    volumes:
      - graphite_data_prod:/opt/graphite/storage
    environment:
      - GRAPHITE_DEBUG=false
    ports:
      - 8082:80 # nginx
      - 2103:2003 # carbon receiver - plaintext
      - 2104:2004 # carbon receiver - pickle
      - 2123:2023 # carbon - plaintext
      - 2124:2024 # carbon - pickle
      - 8180:8080 # Graphite internal gunicorn port 
      - 8127:8125/udp # statsd
      - 8128:8126 # statsd admin

volumes:
  graphite_data_prod: {}