apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dev
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
        - name: app-dev
          image: thetwaihtut/docker_app-dev:v1.0.0
          envFrom:
            - configMapRef:
                name: app-config