apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphite-dev
  template:
    metadata:
      labels:
        app: graphite-dev
    spec:
      containers:
        - name: graphite-dev
          image: graphiteapp/graphite-statsd:1.1.10-5
          ports:
            - containerPort: 80
            - containerPort: 2003
            - containerPort: 2004
            - containerPort: 2023
            - containerPort: 2024
            - containerPort: 8080
            - containerPort: 8125
              protocol: UDP
            - containerPort: 8126
          env:
            - name: GRAPHITE_DEBUG
              value: "true"
          volumeMounts:
            - name: graphite-data
              mountPath: /opt/graphite/storage
      volumes:
        - name: graphite-data
          persistentVolumeClaim:
            claimName: graphite-data-dev
