apiVersion: v1
kind: Service
metadata:
  name: statsd-http-dev
  namespace: dev
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    name: graphite-www
  type: LoadBalancer  
  selector:
    app: graphite-dev